name: Lint CI workflows

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  check-ci-workflows:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          repository: ${{ github.repository }}
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.x'
      - name: Run zizmor
        env:
          GH_TOKEN: ${{ github.token }}
          FORCE_COLOR: 1
        run: pipx run zizmor --format=github .github/workflows/*.yml
