name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-pre-commit:
    uses: ./.github/workflows/pre-commit.yml
  test-mkdocs:
    uses: ./.github/workflows/mkdocs.yml
  test-sphinx:
    uses: ./.github/workflows/sphinx.yml
    with:
      path-to-doc: .
  test-py-coverage:
    uses: ./.github/workflows/py-coverage.yml
  test-py-publish:
    uses: ./.github/workflows/py-publish.yml
  test-release-drafter:
    uses: ./.github/workflows/release-drafter.yml
