name: MkDocs Deploy

on:
  workflow_call:

jobs:
  mkdocs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --group docs
      - name: Check mkdocs build
        if: github.ref != 'refs/heads/main'
        run: uv run mkdocs build
      - name: Upload docs build as artifact
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_docs
          path: ${{ github.workspace }}/site
      - name: Build docs and deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name 'github-actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          uv run mkdocs gh-deploy --force
