name: Release Drafter

on:
  workflow_call:
    inputs:
      commitish:
        required: false
        type: string
        default: "main"
        description: The release target, i.e. branch or commit it should point to.

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Draft your next Release notes as Pull Requests are merged into the default branch
      - uses: release-drafter/release-drafter@v6
        with:
          commitish: '${{ inputs.commitish }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
