name: Sphinx Deploy

on:
  workflow_call:
    inputs:
      path-to-doc:
        required: true
        type: string
        default: docs/_build/html
        description: The docs path name

jobs:
  sphinx-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5
      - uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b #v6

      - name: Install dependencies
        run: uv sync --group docs

      - name: Build docs
        run: uv run sphinx-build docs ${{ inputs.path-to-doc }}

      - name: Upload docs build as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4
        with:
          name: ${{ github.event.repository.name }}_docs
          path: ${{ github.workspace }}/${{ inputs.path-to-doc }}

      - name: Upload to github pages
        # only publish doc changes from main branch
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e #v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ inputs.path-to-doc }}
