name: Sphinx Deploy

on:
  workflow_call:
  inputs:
    artifact-name:
      required: true
      default: cpp-linter_docs
      type: string
      description: The docs artifact name
    doc-path:
      required: true
      type: string
      default: docs/_build/html
      description: The docs path name

jobs:
  sphinx-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install sphinx-immaterial

      - name: Build docs
        if: github.ref != 'refs/heads/main'
        run: sphinx-build docs ${{ inputs.doc-path }}

      - name: Upload docs build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ github.workspace }}/${{ inputs.doc-path }}

      - name: Upload to github pages
        # only publish doc changes from main branch
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ inputs.doc-path }}
