name: Sphinx Deploy

on:
  workflow_call:
    inputs:
      path-to-doc:
        required: true
        type: string
        default: docs/_build/html
        description: The docs path name

jobs:
  sphinx-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install sphinx-immaterial -e .

      - name: Build docs
        if: github.ref != 'refs/heads/main'
        run: sphinx-build docs ${{ inputs.path-to-doc }}

      - name: get artifact name
        id: artifact-name
        shell: python
        run: |
          import os
          lib_name = "${{ github.repository }}".split("/")[1]
          with open(os.environ.get("GITHUB_OUTPUT"), "a") as gh_out:
              gh_out.write(f"lib-name={lib_name}\n")

      - name: Upload docs build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.lib-name }}_docs
          path: ${{ github.workspace }}/${{ inputs.path-to-doc }}

      - name: Upload to github pages
        # only publish doc changes from main branch
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ inputs.path-to-doc }}
