name: Tag Release

on:
  workflow_dispatch:
    inputs:
      project:
        description: >-
          Which cpp-linter project do you want to deploy?
        required: true
        type: choice
        options:
          - cpp-linter-action
          - cpp-linter
          - clang-tools-pip
          - cpp-linter-hooks
          - clang-tools-docker
          # add more cpp-linter projects here
          # NOTE: cpp-linter-rs has its own bump-n-release.yml workflow
      component:
        description: >-
          The version component to bump.
          If set to `auto`, then the component will be
          determined based on the git commit history since
          the previous release.
        default: auto
        required: true
        type: choice
        options:
          - auto
          - patch
          - minor
          - major

permissions: {}

jobs:
  create-release:
    # NOTE: This job requires a PAT (stored under `secrets.BUMP_N_RELEASE`).
    # Using the generic `secrets.GITHUB_TOKEN` to create a release will
    # not trigger other CI workflows, namely the release.yml (for deployments).
    runs-on: ubuntu-latest
    # These permissions must be granted by the token stored in `secrets.BUMP_N_RELEASE`
    # permissions:
    #   # write permission needed to create a GitHub release
    #   contents: write
    #   # read permission needed to parse PRs corresponding to commits
    #   pull-requests: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # credentials needed because `git` is used in tag-release.nu script
          persist-credentials: true
          repository: cpp-linter/${{ inputs.project }}
          path: project-repo
          token: ${{ secrets.BUMP_N_RELEASE }}
          fetch-depth: 0
          fetch-tags: true
      - name: Checkout org repo
        # needed for certain config and script files
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          repository: cpp-linter/.github
          path: org-repo
      - name: Install uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
        with:
          enable-cache: true
          cache-dependency-glob: ${{ github.workspace }}/project-repo/uv.lock
      - name: Setup Nu shell
        uses: hustcer/setup-nu@985d59ec83ae3e3418f9d36471cda38b9d8b9879 # v3.20
        with:
          version: ${{ vars.NUSHELL_VERSION || '*' }}
      - name: Tag version (${{ inputs.component }})
        env:
          UV_CONSTRAINT: ${{ github.workspace }}/org-repo/.github/requirements.txt
          # GITHUB_TOKEN used by git-cliff and gh-cli
          GITHUB_TOKEN: ${{ secrets.BUMP_N_RELEASE }}
          # Some gh-cli commands expect GH_TOKEN instead of GITHUB_TOKEN
          GH_TOKEN: ${{ secrets.BUMP_N_RELEASE }}
          # for git-cliff exclusively
          GITHUB_REPO: cpp-linter/${{ inputs.project }}
          GIT_CLIFF_CONFIG: ${{ github.workspace }}/org-repo/.github/cliff.toml
          INPUTS_COMPONENT: ${{ inputs.component }}
        working-directory: project-repo
        run: >-
          nu
          ${{ github.workspace }}/org-repo/.github/workflows/tag-release.nu
          "${INPUTS_COMPONENT}"
